services:
  db:
    image: mysql:8.2.0
    ports:
      - "${DB_PORT}:3306"
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
