services:
  db:
    image: mysql:8.2.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    restart: unless-stopped
    networks:
      - mysql-network
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "${DB_USERNAME}",
          "-p${DB_PASSWORD}",
        ]
      timeout: 20s
      retries: 10
      start_period: 40s
      interval: 10s

  app:
    build: .
    command: sh -c "npm run db:run && npm run dev"
    container_name: typeorm-app-container
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    ports:
      - "${PORT}:3000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - DB_HOST=db # Use service name instead of localhost
      - DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@db:3306/${DB_DATABASE}
    networks:
      - mysql-network
    restart: unless-stopped

volumes:
  mysql-data:
    driver: local

networks:
  mysql-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
          gateway: 172.16.0.1
